envVarGroups:
  - name: shared-secrets
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        sync: false

  - name: shared-db-credentials
    envVars:
      - key: DB_PORT
        value: "5432"
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false

  - name: shared-rabbitmq
    envVars:
      - key: RABBITMQ_URL
        sync: false
      - key: RABBITMQ_USER
        sync: false
      - key: RABBITMQ_PASS
        sync: false

  - name: shared-redis
    envVars:
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        sync: false

services:
  - type: web
    name: api-gateway
    env: docker
    rootDir: api-gateway
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-secrets
      - fromGroup: shared-rabbitmq
      - key: NODE_ENV
        value: production
      - key: GATEWAY_PORT
        value: "3000"
      - key: USER_SERVICE_HOST
        value: user-service.onrender.com
      - key: USER_SERVICE_PORT
        value: "443"
      - key: MENU_SERVICE_HOST
        value: menu-service.onrender.com
      - key: MENU_SERVICE_PORT
        value: "443"
      - key: ORDER_SERVICE_HOST
        value: order-service.onrender.com
      - key: ORDER_SERVICE_PORT
        value: "443"
      - key: NOTIFICATION_SERVICE_HOST
        value: notification-service.onrender.com
      - key: NOTIFICATION_SERVICE_PORT
        value: "443"
      - key: PAYMENT_SERVICE_HOST
        value: payment-service.onrender.com
      - key: PAYMENT_SERVICE_PORT
        value: "443"
      - key: SWAGGER_USER
        sync: false
      - key: SWAGGER_PASSWORD
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false

  - type: web
    name: user-service
    env: docker
    rootDir: user-service
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-secrets
      - fromGroup: shared-db-credentials
      - fromGroup: shared-rabbitmq
      - fromGroup: shared-redis
      - key: NODE_ENV
        value: production
      - key: USER_PORT
        value: "3001"
      - key: FRONTEND_URL
        sync: false
      - key: USER_DB_HOST
        sync: false
      - key: USER_DB_NAME
        sync: false
      - key: POSTGRES_USER_DB
        sync: false
      - key: MENU_SERVICE_HOST
        value: menu-service.onrender.com
      - key: MENU_SERVICE_PORT
        value: "443"
      - key: USER_DATABASE_URL
        sync: false

  - type: web
    name: menuitems-service
    env: docker
    rootDir: menu-service
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-secrets
      - fromGroup: shared-db-credentials
      - key: NODE_ENV
        value: production
      - key: MENU_PORT
        value: "3002"
      - key: MENU_DB_HOST
        sync: false
      - key: MENU_DB_NAME
        sync: false
      - key: POSTGRES_MENU_DB
        sync: false
      - key: USER_SERVICE_HOST
        value: user-service.onrender.com
      - key: USER_SERVICE_PORT
        value: "443"
      - key: MENU_DATABASE_URL
        sync: false

  - type: web
    name: order-service
    env: docker
    rootDir: order-service
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-secrets
      - fromGroup: shared-db-credentials
      - fromGroup: shared-rabbitmq
      - key: NODE_ENV
        value: production
      - key: ORDER_PORT
        value: "3003"
      - key: MENU_SERVICE_HOST
        value: menu-service.onrender.com
      - key: MENU_SERVICE_PORT
        value: "443"
      - key: ORDER_DB_HOST
        sync: false
      - key: ORDER_DB_NAME
        sync: false
      - key: POSTGRES_ORDER_DB
        sync: false
      - key: ORDER_DATABASE_URL
        sync: false

  - type: web
    name: notification-service
    env: docker
    rootDir: notification-service
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-db-credentials
      - fromGroup: shared-rabbitmq
      - fromGroup: shared-redis
      - key: NODE_ENV
        value: production
      - key: NOTIF_PORT
        value: "3004"
      - key: NOTIF_DB_HOST
        sync: false
      - key: NOTIF_DB_NAME
        sync: false
      - key: POSTGRES_NOTIF_DB
        sync: false
      - key: NOTIF_DATABASE_URL
        sync: false

  - type: web
    name: payment
    env: docker
    rootDir: payment-service
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - fromGroup: shared-db-credentials
      - fromGroup: shared-rabbitmq
      - fromGroup: shared-redis
      - key: NODE_ENV
        value: production
      - key: PAYMENT_PORT
        value: "3005"
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYMENT_CALLBACK_URL
        sync: false
      - key: WEBHOOKSECRET
        sync: false
      - key: BASEURL
        sync: false
      - key: ORDER_SERVICE_HOST
        value: order-service.onrender.com
      - key: ORDER_SERVICE_PORT
        value: "443"
      - key: PAYMENT_DB_HOST
        sync: false
      - key: PAYMENT_DB_NAME
        sync: false
      - key: POSTGRES_PAYMENT_DB
        sync: false
      - key: NOTIFICATION_SERVICE_HOST
        value: notification-service.onrender.com
      - key: NOTIFICATION_SERVICE_PORT
        value: "443"
      - key: PAYMENT_DATABASE_URL
        sync: false