export const USER_SERVICE = 'USER_SERVICE';
export const MENU_ITEM_SERVICE = 'MENU_ITEM_SERVICE';
export const ORDER_SERVICE = 'ORDER_SERVICE';
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
export const PAYMENT_SERVICE = 'PAYMENT_SERVICE';
